export const COLORS = {
  navy: "#002e4c",
  blue: "#53C7FF",
  sky: "#53C7FF",
  blueDark: "#001a2c",
  blueLight: "#003b5c",
  blueAccentLight: "#7dd3fc",
  blueMid: "#00567f",
  amber: "#FFD73F",
  amberDark: "#7d5c10",
  amberLight: "#b8891c",
  amberAccentLight: "#fff4cf",
  amberMid: "#a47a16",
  // Lighter than amberMid for filled shapes (buttons, date badges, selected cells) —
  // too light for small text on white, which stays amberMid.
  amberFill: "#c4962a",
  green: "#3fc920",
  greenDark: "#0d3305",
  greenLight: "#1f6b0f",
  greenAccentLight: "#9ae66b",
  greenMid: "#2f9430",
  purple: "#3c1193",
  pinkDark: "#2e0818",
  pinkLight: "#7d1a45",
  pinkAccentLight: "#ffa8cf",
  pinkMid: "#b52a6b",
  white: "#ffffff",
  red: "#EB5757",
  // Request-to-cancel page theme (destructive action), same roles as the amber/green sets.
  redLight: "#b3261e",
  redDark: "#5c1310",
  redMid: "#c62828",
  redAccentLight: "#ffc9c4",
  redBg: "#fdeded",
  black: "#000000",
  grey: "#817576",
  greenBg: "#E8F8EF",
  amberBg: "#FEF3D9",
  // Pastel yellow theme for the Shifts pages. Pastels are too light for white text,
  // so anything filled with them uses pastelInk for its text and icons.
  pastelYellowLight: "#FFF8D6",
  pastelYellow: "#FFEFA6",
  pastelYellowDeep: "#FFE27A",
  pastelYellowBorder: "#EFCB55",
  pastelYellowBg: "#FFFBE8",
  pastelInk: "#5c4508",
  lightGrey: "#F5F7F8",
};